name: Build and Deploy Jekyll with Plugins

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Download Pagefind
        run: |
          mkdir -p _bin
          curl -L https://github.com/CloudCannon/pagefind/releases/latest/download/pagefind-v0.12.0-x86_64-unknown-linux-musl.tar.gz | tar -xz
          mv pagefind _bin/pagefind
          chmod +x _bin/pagefind

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
