name: Build and Deploy Jekyll with Plugins

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Download Pagefind
        run: |
          mkdir -p _bin
          # Get the latest version
          LATEST_VERSION=$(curl -s https://api.github.com/repos/CloudCannon/pagefind/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
          echo "Latest pagefind version: $LATEST_VERSION"
          # Download the binary
          curl -L -o pagefind.tar.gz "https://github.com/CloudCannon/pagefind/releases/download/${LATEST_VERSION}/pagefind-${LATEST_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          tar -xzf pagefind.tar.gz
          mv pagefind _bin/pagefind
          chmod +x _bin/pagefind
          rm pagefind.tar.gz

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Run Pagefind
        run: _bin/pagefind --site _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
